"use strict";

define(["common/js/InputValidator", "artifact/js/CardSet", "artifact/js/CardSubset", "artifact/js/CardType", "artifact/js/Sphere", "artifact/js/Trait"],
   function(InputValidator, CardSet, CardSubset, CardType, Sphere, Trait)
   {
      var AllyCard = {
         ANBORN_TBOG: "anbornTBoG",
         ANBORN_TLOS: "anbornTLoS",
         ANFALAS_HERDSMAN: "anfalasHerdsman",
         ARWEN_UNDOMIEL: "arwenUndomiel",
         BARLIMAN_BUTTERBUR: "barlimanButterbur",
         BEECHBONE: "beechbone",
         BEORN: "beorn",
         BEORNING_BEEKEEPER: "beorningBeekeeper",
         BIFUR: "bifur",
         BILBO_BAGGINS: "bilboBaggins",
         BILL_THE_PONY: "billThePony",
         BLUE_MOUNTAIN_TRADER: "blueMountainTrader",
         BOFUR_OHAUH: "bofurOHaUH",
         BOFUR_TRG: "bofurTRG",
         BOMBUR: "bombur",
         BOOMING_ENT: "boomingEnt",
         BOROMIR: "boromir",
         BROK_IRONFIST: "brokIronfist",
         CELDUIN_TRAVELER: "celduinTraveler",
         CITADEL_CUSTODIAN: "citadelCustodian",
         CURIOUS_BRANDYBUCK: "curiousBrandybuck",
         DAMROD: "damrod",
         DAUGHTER_OF_THE_NIMRODEL: "daughterOfTheNimrodel",
         DEFENDER_OF_RAMMAS: "defenderOfRammas",
         DEFENDER_OF_THE_NAITH: "defenderOfTheNaith",
         DENETHOR: "denethor",
         DERNDINGLE_WARRIOR: "derndingleWarrior",
         DESCENDANT_OF_THORONDOR: "descendantOfThorondor",
         DORI: "dori",
         DUNEDAIN_HUNTER: "dunedainHunter",
         DUNEDAIN_WANDERER: "dunedainWanderer",
         DUNEDAIN_WATCHER: "dunedainWatcher",
         DWALIN: "dwalin",
         EAGLES_OF_THE_MISTY_MOUNTAINS: "eaglesOfTheMistyMountains",
         EAST_ROAD_RANGER: "eastRoadRanger",
         ELFHELM: "elfhelm",
         ELROND: "elrond",
         ELVEN_JEWELER: "elvenJeweler",
         EMERY: "emery",
         ENVOY_OF_PELARGIR: "envoyOfPelargir",
         EOMUND: "eomund",
         EOTHAIN: "eothain",
         EREBOR_BATTLE_MASTER: "ereborBattleMaster",
         EREBOR_HAMMERSMITH: "ereborHammersmith",
         EREBOR_RECORD_KEEPER: "ereborRecordKeeper",
         ERED_NIMRAIS_PROSPECTOR: "eredNimraisProspector",
         ERESTOR: "erestor",
         ERRAND_RIDER: "errandRider",
         ESCORT_FROM_EDORAS: "escortFromEdoras",
         ETHIR_SWORDSMAN: "ethirSwordsman",
         FARAMIR: "faramir",
         FARMER_MAGGOT: "farmerMaggot",
         FILI: "fili",
         FORLONG: "forlong",
         FORNOST_BOWMAN: "fornostBowman",
         GALADHON_ARCHER: "galadhonArcher",
         GALADHRIM_HEALER: "galadhrimHealer",
         GALADHRIM_MINSTREL: "galadhrimMinstrel",
         GALADHRIM_WEAVER: "galadhrimWeaver",
         GALADRIEL: "galadriel",
         GALADRIELS_HANDMAIDEN: "galadrielsHandmaiden",
         GALDOR_OF_THE_HAVENS: "galdorOfTheHavens",
         GAMLING: "gamling",
         GANDALF_CORE: "gandalfCore",
         GANDALF_OHAUH: "gandalfOHaUH",
         GILDOR_INGLORION: "gildorInglorion",
         GIMLI: "gimli",
         GLEOWINE: "gleowine",
         GLOIN: "gloin",
         GONDORIAN_SPEARMAN: "gondorianSpearman",
         GREYFLOOD_WANDERER: "greyfloodWanderer",
         GUARD_OF_THE_CITADEL: "guardOfTheCitadel",
         GUARDIAN_OF_ARNOR: "guardianOfArnor",
         GUTHLAF: "guthlaf",
         GWAIHIR: "gwaihir",
         HALDIR_OF_LORIEN: "haldirOfLorien",
         HAMA: "hama",
         HARBOR_MASTER: "harborMaster",
         HENAMARTH_RIVERSONG: "henamarthRiversong",
         HENNETH_ANNUN_GUARD: "hennethAnnunGuard",
         HERALD_OF_ANORIEN: "heraldOfAnorien",
         HONOUR_GUARD: "honourGuard",
         HORSEBACK_ARCHER: "horsebackArcher",
         HUNTER_OF_LAMEDON: "hunterOfLamedon",
         IMLADRIS_STARGAZER: "imladrisStargazer",
         INGOLD: "ingold",
         ISENGARD_MESSENGER: "isengardMessenger",
         ITHILIEN_ARCHER: "ithilienArcher",
         ITHILIEN_LOOKOUT: "ithilienLookout",
         ITHILIEN_TRACKER: "ithilienTracker",
         KEEN_EYED_TOOK: "keenEyedTook",
         KILI: "kili",
         KNIGHT_OF_MINAS_TIRITH: "knightOfMinasTirith",
         KNIGHTS_OF_THE_SWAN: "knightsOfTheSwan",
         LANDROVAL: "landroval",
         LEGOLAS: "legolas",
         LINDIR: "lindir",
         LINDON_NAVIGATOR: "lindonNavigator",
         LONGBEARD_ELDER: "longbeardElder",
         LONGBEARD_MAP_MAKER: "longbeardMapMaker",
         LONGBEARD_ORC_SLAYER: "longbeardOrcSlayer",
         LONGBEARD_SENTRY: "longbeardSentry",
         LORIEN_GUIDE: "lorienGuide",
         MABLUNG: "mablung",
         MASTER_OF_LORE: "masterOfLore",
         MASTER_OF_THE_FORGE: "masterOfTheForge",
         MINAS_TIRITH_LAMPWRIGHT: "minasTirithLampwright",
         MINER_OF_THE_IRON_HILLS: "minerOfTheIronHills",
         MIRKWOOD_PIONEER: "mirkwoodPioneer",
         MIRKWOOD_RUNNER: "mirkwoodRunner",
         MITHLOND_SEA_WATCHER: "mithlondSeaWatcher",
         NAITH_GUIDE: "naithGuide",
         NORTHERN_TRACKER: "northernTracker",
         OROPHIN: "orophin",
         ORTHANC_GUARD: "orthancGuard",
         QUICKBEAM: "quickbeam",
         PELARGIR_SHIP_CAPTAIN: "pelargirShipCaptain",
         PELARGIR_SHIPWRIGHT: "pelargirShipwright",
         RADAGAST: "radagast",
         RANGER_OF_CARDOLAN: "rangerOfCardolan",
         RAVENHILL_SCOUT: "ravenhillScout",
         RIDER_OF_THE_MARK: "riderOfTheMark",
         RIVENDELL_MINSTREL: "rivendellMinstrel",
         RIVENDELL_SCOUT: "rivendellScout",
         RUMIL: "rumil",
         SAILOR_OF_LUNE: "sailorOfLune",
         SARN_FORD_SENTRY: "sarnFordSentry",
         SARUMAN: "saruman",
         SILVAN_REFUGEE: "silvanRefugee",
         SILVAN_TRACKER: "silvanTracker",
         SILVERLODE_ARCHER: "silverlodeArcher",
         SKINBARK: "skinbark",
         SNOWBOURN_SCOUT: "snowbournScout",
         SON_OF_ARNOR: "sonOfArnor",
         SQUIRE_OF_THE_CITADEL: "squireOfTheCitadel",
         THE_RIDDERMARKS_FINEST: "theRiddermarksFinest",
         TREEBEARD: "treebeard",
         TROLLSHAW_SCOUT: "trollshawScout",
         VASSAL_OF_THE_WINDLORD: "vassalOfTheWindlord",
         VETERAN_AXEHAND: "veteranAxehand",
         VETERAN_OF_NANDUHIRION: "veteranOfNanduhirion",
         VETERAN_OF_OSGILIATH: "veteranOfOsgiliath",
         WANDERING_ENT: "wanderingEnt",
         WANDERING_TOOK: "wanderingTook",
         WARDEN_OF_ANNUMINAS: "wardenOfAnnuminas",
         WARDEN_OF_HEALING: "wardenOfHealing",
         WARDEN_OF_HELMS_DEEP: "wardenOfHelmsDeep",
         WARDEN_OF_THE_HAVENS: "wardenOfTheHavens",
         WARRIOR_OF_LOSSARNACH: "warriorOfLossarnach",
         WATCHER_OF_THE_BRUINEN: "watcherOfTheBruinen",
         WEATHER_HILLS_WATCHMAN: "weatherHillsWatchman",
         WELLINGHALL_PRESERVER: "wellinghallPreserver",
         WESTFOLD_HORSE_BREAKER: "westfoldHorseBreaker",
         WESTFOLD_HORSE_BREEDER: "westfoldHorseBreeder",
         WESTFOLD_OUTRIDER: "westfoldOutrider",
         WEST_ROAD_TRAVELLER: "westRoadTraveller",
         WHITE_TOWER_WATCHMAN: "whiteTowerWatchman",
         WINGED_GUARDIAN: "wingedGuardian",
         ZIGIL_MINER: "zigilMiner",

         properties:
         {
            "anbornTBoG":
            {
               name: "Anborn",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
               key: "anbornTBoG",
            },
            "anbornTLoS":
            {
               name: "Anborn",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_LAND_OF_SHADOW,
               cardSetNumber: 4,
               key: "anbornTLoS",
            },
            "anfalasHerdsman":
            {
               name: "Anfalas Herdsman",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.OUTLANDS],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS1_THE_STEWARDS_FEAR,
               key: "anfalasHerdsman",
            },
            "arwenUndomiel":
            {
               name: "Arwen Undómiel",
               isUnique: true,
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.NOBLE],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D3_THE_WATCHER_IN_THE_WATER,
               key: "arwenUndomiel",
            },
            "barlimanButterbur":
            {
               name: "Barliman Butterbur",
               isUnique: true,
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.BREE],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_BLACK_RIDERS,
               key: "barlimanButterbur",
            },
            "beechbone":
            {
               name: "Beechbone",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 2,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA5_THE_BATTLE_OF_CARN_DUM,
               cardSetNumber: 118,
               key: "beechbone",
            },
            "beorn":
            {
               name: "Beorn",
               isUnique: true,
               cost: 6,
               willpower: 1,
               attack: 3,
               defense: 3,
               hitPoints: 6,
               traitKeys: [Trait.BEORNING, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.CORE,
               key: "beorn",
            },
            "beorningBeekeeper":
            {
               name: "Beorning Beekeeper",
               cost: 4,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.BEORNING],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM2_CONFLICT_AT_THE_CARROCK,
               key: "beorningBeekeeper",
            },
            "bifur":
            {
               name: "Bifur",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.ON_THE_DOORSTEP,
               key: "bifur",
            },
            "bilboBaggins":
            {
               name: "Bilbo Baggins",
               isUnique: true,
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.HOBBIT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_ROAD_DARKENS,
               cardSetNumber: "006",
               key: "bilboBaggins",
            },
            "billThePony":
            {
               name: "Bill the Pony",
               isUnique: true,
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.CREATURE, Trait.PONY],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_BLACK_RIDERS,
               key: "billThePony",
            },
            "blueMountainTrader":
            {
               name: "Blue Mountain Trader",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM1_THE_DUNLAND_TRAP,
               cardSetNumber: 6,
               key: "blueMountainTrader",
            },
            "bofurOHaUH":
            {
               name: "Bofur",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 2,
               defense: 0,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
               key: "bofurOHaUH",
            },
            "bofurTRG":
            {
               name: "Bofur",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D1_THE_REDHORN_GATE,
               key: "bofurTRG",
            },
            "bombur":
            {
               name: "Bombur",
               isUnique: true,
               cost: 3,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D2_ROAD_TO_RIVENDELL,
               key: "bombur",
            },
            "boomingEnt":
            {
               name: "Booming Ent",
               cost: 2,
               willpower: 0,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM6_THE_ANTLERED_CROWN,
               cardSetNumber: 141,
               key: "boomingEnt",
            },
            "boromir":
            {
               name: "Boromir",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_ROAD_DARKENS,
               cardSetNumber: "004",
               key: "boromir",
            },
            "brokIronfist":
            {
               name: "Brok Ironfist",
               isUnique: true,
               cost: 6,
               willpower: 2,
               attack: 2,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "brokIronfist",
            },
            "celduinTraveler":
            {
               name: "Celduin Traveler",
               cost: 3,
               willpower: 2,
               attack: 0,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DALE, Trait.SCOUT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM4_THE_NIN_IN_EILPH,
               cardSetNumber: 89,
               key: "celduinTraveler",
            },
            "citadelCustodian":
            {
               name: "Citadel Custodian",
               cost: 5,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "citadelCustodian",
            },
            "curiousBrandybuck":
            {
               name: "Curious Brandybuck",
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.HOBBIT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
               cardSetNumber: 6,
               key: "curiousBrandybuck",
            },
            "damrod":
            {
               name: "Damrod",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 2,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "damrod",
            },
            "daughterOfTheNimrodel":
            {
               name: "Daughter of the Nimrodel",
               cost: 3,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.CORE,
               key: "daughterOfTheNimrodel",
            },
            "defenderOfRammas":
            {
               name: "Defender of Rammas",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 4,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "defenderOfRammas",
            },
            "defenderOfTheNaith":
            {
               name: "Defender of the Naith",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.SILVAN, Trait.WARRIOR],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM3_TROUBLE_IN_THARBAD,
               cardSetNumber: 65,
               key: "defenderOfTheNaith",
            },
            "denethor":
            {
               name: "Denethor",
               isUnique: true,
               cost: 4,
               willpower: 3,
               attack: 1,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.NOBLE],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS3_ENCOUNTER_AT_AMON_DIN,
               key: "denethor",
            },
            "derndingleWarrior":
            {
               name: "Derndingle Warrior",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ENT, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA2_ESCAPE_FROM_MOUNT_GRAM,
               cardSetNumber: 31,
               key: "derndingleWarrior",
            },
            "descendantOfThorondor":
            {
               name: "Descendant of Thorondor",
               cost: 4,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
               key: "descendantOfThorondor",
            },
            "dori":
            {
               name: "Dori",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
               key: "dori",
            },
            "dunedainHunter":
            {
               name: "Dúnedain Hunter",
               cost: 0,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_LOST_REALM,
               cardSetNumber: 4,
               key: "dunedainHunter",
            },
            "dunedainWanderer":
            {
               name: "Dúnedain Wanderer",
               cost: 5,
               willpower: 1,
               attack: 2,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D2_ROAD_TO_RIVENDELL,
               key: "dunedainWanderer",
            },
            "dunedainWatcher":
            {
               name: "Dúnedain Watcher",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
               key: "dunedainWatcher",
            },
            "dwalin":
            {
               name: "Dwalin",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.ON_THE_DOORSTEP,
               key: "dwalin",
            },
            "eaglesOfTheMistyMountains":
            {
               name: "Eagles of the Misty Mountains",
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 2,
               hitPoints: 4,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM6_RETURN_TO_MIRKWOOD,
               key: "eaglesOfTheMistyMountains",
            },
            "eastRoadRanger":
            {
               name: "East Road Ranger",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.SCOUT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
               cardSetNumber: 8,
               key: "eastRoadRanger",
            },
            "elfhelm":
            {
               name: "Elfhelm",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ROHAN, Trait.WARRIOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
               key: "elfhelm",
            },
            "elrond":
            {
               name: "Elrond",
               isUnique: true,
               cost: 3,
               willpower: 3,
               attack: 2,
               defense: 3,
               hitPoints: 3,
               traitKeys: [Trait.NOLDOR, Trait.HEALER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_ROAD_DARKENS,
               cardSetNumber: "005",
               key: "elrond",
            },
            "elvenJeweler":
            {
               name: "Elven Jeweler",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.CRAFTSMAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA2_ESCAPE_FROM_MOUNT_GRAM,
               cardSetNumber: 33,
               key: "elvenJeweler",
            },
            "emery":
            {
               name: "Emery",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
               key: "emery",
            },
            "envoyOfPelargir":
            {
               name: "Envoy of Pelargir",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "envoyOfPelargir",
            },
            "eomund":
            {
               name: "Éomund",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM2_CONFLICT_AT_THE_CARROCK,
               key: "eomund",
            },
            "eothain":
            {
               name: "Éothain",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.ROHAN, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA6_THE_DREAD_REALM,
               key: "eothain",
            },
            "ereborBattleMaster":
            {
               name: "Erebor Battle Master",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D4_THE_LONG_DARK,
               key: "ereborBattleMaster",
            },
            "ereborHammersmith":
            {
               name: "Erebor Hammersmith",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF, Trait.CRAFTSMAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.CORE,
               key: "ereborHammersmith",
            },
            "ereborRecordKeeper":
            {
               name: "Erebor Record Keeper",
               cost: 1,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.KHAZAD_DUM,
               key: "ereborRecordKeeper",
            },
            "eredNimraisProspector":
            {
               name: "Ered Nimrais Prospector",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS6_THE_MORGUL_VALE,
               key: "eredNimraisProspector",
            },
            "erestor":
            {
               name: "Erestor",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 0,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D4_THE_LONG_DARK,
               key: "erestor",
            },
            "errandRider":
            {
               name: "Errand-rider",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "errandRider",
            },
            "escortFromEdoras":
            {
               name: "Escort from Edoras",
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
               key: "escortFromEdoras",
            },
            "ethirSwordsman":
            {
               name: "Ethir Swordsman",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.OUTLANDS],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS1_THE_STEWARDS_FEAR,
               key: "ethirSwordsman",
            },
            "faramir":
            {
               name: "Faramir",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 1,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.NOBLE, Trait.RANGER],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "faramir",
            },
            "farmerMaggot":
            {
               name: "Farmer Maggot",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.HOBBIT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_BLACK_RIDERS,
               key: "farmerMaggot",
            },
            "fili":
            {
               name: "Fili",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
               key: "fili",
            },
            "forlong":
            {
               name: "Forlong",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.OUTLANDS],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS2_THE_DRUADAN_FOREST,
               key: "forlong",
            },
            "fornostBowman":
            {
               name: "Fornost Bowman",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA6_THE_DREAD_REALM,
               key: "fornostBowman",
            },
            "galadhonArcher":
            {
               name: "Galadhon Archer",
               cost: 2,
               willpower: 0,
               attack: 2,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM4_THE_NIN_IN_EILPH,
               cardSetNumber: 87,
               key: "galadhonArcher",
            },
            "galadhrimHealer":
            {
               name: "Galadhrim Healer",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN, Trait.HEALER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA6_THE_DREAD_REALM,
               key: "galadhrimHealer",
            },
            "galadhrimMinstrel":
            {
               name: "Galadhrim Minstrel",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN, Trait.MINSTREL],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM3_TROUBLE_IN_THARBAD,
               cardSetNumber: 63,
               key: "galadhrimMinstrel",
            },
            "galadhrimWeaver":
            {
               name: "Galadhrim Weaver",
               cost: 1,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN, Trait.CRAFTSMAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA4_THE_TREACHERY_OF_RHUDAUR,
               cardSetNumber: 89,
               key: "galadhrimWeaver",
            },
            "galadriel":
            {
               name: "Galadriel",
               isUnique: true,
               cost: 3,
               willpower: 3,
               attack: 0,
               defense: 0,
               hitPoints: 3,
               traitKeys: [Trait.NOLDOR, Trait.NOBLE],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_ROAD_DARKENS,
               cardSetNumber: "003",
               key: "galadriel",
            },
            "galadrielsHandmaiden":
            {
               name: "Galadriel's Handmaiden",
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM5_CELEBRIMBORS_SECRET,
               cardSetNumber: 117,
               key: "galadrielsHandmaiden",
            },
            "galdorOfTheHavens":
            {
               name: "Galdor of the Havens",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA4_THE_TREACHERY_OF_RHUDAUR,
               cardSetNumber: 91,
               key: "galdorOfTheHavens",
            },
            "gamling":
            {
               name: "Gamling",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN, Trait.WARRIOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_LAND_OF_SHADOW,
               cardSetNumber: 7,
               key: "gamling",
            },
            "gandalfCore":
            {
               name: "Gandalf",
               isUnique: true,
               cost: 5,
               willpower: 4,
               attack: 4,
               defense: 4,
               hitPoints: 4,
               traitKeys: [Trait.ISTARI],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.CORE,
               key: "gandalfCore",
            },
            "gandalfOHaUH":
            {
               name: "Gandalf",
               isUnique: true,
               cost: 5,
               willpower: 4,
               attack: 4,
               defense: 4,
               hitPoints: 4,
               traitKeys: [Trait.ISTARI],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
               key: "gandalfOHaUH",
            },
            "gildorInglorion":
            {
               name: "Gildor Inglorion",
               isUnique: true,
               cost: 5,
               willpower: 3,
               attack: 2,
               defense: 3,
               hitPoints: 3,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
               key: "gildorInglorion",
            },
            "gimli":
            {
               name: "Gimli",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
               cardSetNumber: 4,
               key: "gimli",
            },
            "gleowine":
            {
               name: "Gléowine",
               isUnique: true,
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.MINSTREL, Trait.ROHAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.CORE,
               key: "gleowine",
            },
            "gloin":
            {
               name: "Glóin",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.ON_THE_DOORSTEP,
               key: "gloin",
            },
            "gondorianSpearman":
            {
               name: "Gondorian Spearman",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.CORE,
               key: "gondorianSpearman",
            },
            "greyfloodWanderer":
            {
               name: "Greyflood Wanderer",
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN, Trait.SCOUT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM2_THE_THREE_TRIALS,
               cardSetNumber: 30,
               key: "greyfloodWanderer",
            },
            "guardOfTheCitadel":
            {
               name: "Guard of the Citadel",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "guardOfTheCitadel",
            },
            "guardianOfArnor":
            {
               name: "Guardian of Arnor",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA5_THE_BATTLE_OF_CARN_DUM,
               cardSetNumber: 116,
               key: "guardianOfArnor",
            },
            "guthlaf":
            {
               name: "Guthlaf",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
               key: "guthlaf",
            },
            "gwaihir":
            {
               name: "Gwaihir",
               isUnique: true,
               cost: 5,
               willpower: 2,
               attack: 3,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM3_TROUBLE_IN_THARBAD,
               cardSetNumber: 59,
               key: "gwaihir",
            },
            "haldirOfLorien":
            {
               name: "Haldir of Lórien",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
               key: "haldirOfLorien",
            },
            "hama":
            {
               name: "Háma",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN, Trait.WARRIOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
               cardSetNumber: 7,
               key: "hama",
            },
            "harborMaster":
            {
               name: "Harbor Master",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS2_THE_DRUADAN_FOREST,
               key: "harborMaster",
            },
            "henamarthRiversong":
            {
               name: "Henamarth Riversong",
               isUnique: true,
               cost: 1,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.CORE,
               key: "henamarthRiversong",
            },
            "hennethAnnunGuard":
            {
               name: "Henneth Annûn Guard",
               cost: 3,
               willpower: 0,
               attack: 2,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM5_CELEBRIMBORS_SECRET,
               cardSetNumber: 115,
               key: "hennethAnnunGuard",
            },
            "heraldOfAnorien":
            {
               name: "Herald of Anórien",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM3_TROUBLE_IN_THARBAD,
               cardSetNumber: 57,
               key: "heraldOfAnorien",
            },
            "honourGuard":
            {
               name: "Honour Guard",
               cost: 2,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
               cardSetNumber: 4,
               key: "honourGuard",
            },
            "horsebackArcher":
            {
               name: "Horseback Archer",
               cost: 3,
               willpower: 0,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN, Trait.ARCHER],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.CORE,
               key: "horsebackArcher",
            },
            "hunterOfLamedon":
            {
               name: "Hunter of Lamedon",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR, Trait.OUTLANDS],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "hunterOfLamedon",
            },
            "imladrisStargazer":
            {
               name: "Imladris Stargazer",
               cost: 2,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D5_FOUNDATIONS_OF_STONE,
               key: "imladrisStargazer",
            },
            "ingold":
            {
               name: "Ingold",
               isUnique: true,
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
               cardSetNumber: 2,
               key: "ingold",
            },
            "isengardMessenger":
            {
               name: "Isengard Messenger",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.ISENGARD],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
               cardSetNumber: 5,
               key: "isengardMessenger",
            },
            "ithilienArcher":
            {
               name: "Ithilien Archer",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS3_ENCOUNTER_AT_AMON_DIN,
               key: "ithilienArcher",
            },
            "ithilienLookout":
            {
               name: "Ithilien Lookout",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM1_THE_DUNLAND_TRAP,
               cardSetNumber: 8,
               key: "ithilienLookout",
            },
            "ithilienTracker":
            {
               name: "Ithilien Tracker",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 0,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "ithilienTracker",
            },
            "keenEyedTook":
            {
               name: "Keen-eyed Took",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.HOBBIT],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
               key: "keenEyedTook",
            },
            "kili":
            {
               name: "Kili",
               isUnique: true,
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.OVER_HILL_AND_UNDER_HILL,
               key: "kili",
            },
            "knightOfMinasTirith":
            {
               name: "Knight of Minas Tirith",
               cost: 3,
               willpower: 0,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS4_ASSAULT_ON_OSGILIATH,
               key: "knightOfMinasTirith",
            },
            "knightsOfTheSwan":
            {
               name: "Knights of the Swan",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.OUTLANDS],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS1_THE_STEWARDS_FEAR,
               key: "knightsOfTheSwan",
            },
            "landroval":
            {
               name: "Landroval",
               isUnique: true,
               cost: 5,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 4,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
               key: "landroval",
            },
            "legolas":
            {
               name: "Legolas",
               isUnique: true,
               cost: 4,
               willpower: 1,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.SILVAN, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
               cardSetNumber: 5,
               key: "legolas",
            },
            "lindir":
            {
               name: "Lindir",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA5_THE_BATTLE_OF_CARN_DUM,
               cardSetNumber: 120,
               key: "lindir",
            },
            "lindonNavigator":
            {
               name: "Lindon Navigator",
               cost: 2,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.SCOUT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_GREY_HAVENS,
               cardSetNumber: 9,
               key: "lindonNavigator",
            },
            "longbeardElder":
            {
               name: "Longbeard Elder",
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D5_FOUNDATIONS_OF_STONE,
               key: "longbeardElder",
            },
            "longbeardMapMaker":
            {
               name: "Longbeard Map Maker",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM2_CONFLICT_AT_THE_CARROCK,
               key: "longbeardMapMaker",
            },
            "longbeardOrcSlayer":
            {
               name: "Longbeard Orc Slayer",
               cost: 4,
               willpower: 0,
               attack: 2,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "longbeardOrcSlayer",
            },
            "longbeardSentry":
            {
               name: "Longbeard Sentry",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA3_ACROSS_THE_ETTENMOORS,
               cardSetNumber: 57,
               key: "longbeardSentry",
            },
            "lorienGuide":
            {
               name: "Lórien Guide",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.SILVAN, Trait.SCOUT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.CORE,
               key: "lorienGuide",
            },
            "mablung":
            {
               name: "Mablung",
               isUnique: true,
               cost: 2,
               willpower: 2,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.RANGER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_LAND_OF_SHADOW,
               cardSetNumber: 5,
               key: "mablung",
            },
            "masterOfLore":
            {
               name: "Master of Lore",
               cost: 3,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.HEIRS_OF_NUMENOR,
               key: "masterOfLore",
            },
            "masterOfTheForge":
            {
               name: "Master of the Forge",
               cost: 2,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.NOLDOR, Trait.CRAFTSMAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D6_SHADOW_AND_FLAME,
               key: "masterOfTheForge",
            },
            "minasTirithLampwright":
            {
               name: "Minas Tirith Lampwright",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR, Trait.CRAFTSMAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS3_ENCOUNTER_AT_AMON_DIN,
               key: "minasTirithLampwright",
            },
            "minerOfTheIronHills":
            {
               name: "Miner of the Iron Hills",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.CORE,
               key: "minerOfTheIronHills",
            },
            "mirkwoodPioneer":
            {
               name: "Mirkwood Pioneer",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.WOODMAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM4_THE_NIN_IN_EILPH,
               cardSetNumber: 91,
               key: "mirkwoodPioneer",
            },
            "mirkwoodRunner":
            {
               name: "Mirkwood Runner",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.SILVAN, Trait.SCOUT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM6_RETURN_TO_MIRKWOOD,
               key: "mirkwoodRunner",
            },
            "mithlondSeaWatcher":
            {
               name: "Mithlond Sea-watcher",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_GREY_HAVENS,
               cardSetNumber: 3,
               key: "mithlondSeaWatcher",
            },
            "naithGuide":
            {
               name: "Naith Guide",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN, Trait.SCOUT],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM1_THE_DUNLAND_TRAP,
               cardSetNumber: 2,
               key: "naithGuide",
            },
            "northernTracker":
            {
               name: "Northern Tracker",
               cost: 4,
               willpower: 1,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.CORE,
               key: "northernTracker",
            },
            "orophin":
            {
               name: "Orophin",
               isUnique: true,
               cost: 3,
               willpower: 2,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.SILVAN, Trait.SCOUT],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM5_CELEBRIMBORS_SECRET,
               cardSetNumber: 114,
               key: "orophin",
            },
            "orthancGuard":
            {
               name: "Orthanc Guard",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.ISENGARD],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
               cardSetNumber: 4,
               key: "orthancGuard",
            },
            "pelargirShipCaptain":
            {
               name: "Pelargir Ship Captain",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS6_THE_MORGUL_VALE,
               key: "pelargirShipCaptain",
            },
            "pelargirShipwright":
            {
               name: "Pelargir Shipwright",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR, Trait.CRAFTSMAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS4_ASSAULT_ON_OSGILIATH,
               key: "pelargirShipwright",
            },
            "quickbeam":
            {
               name: "Quickbeam",
               isUnique: true,
               cost: 2,
               willpower: 2,
               attack: 3,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_TREASON_OF_SARUMAN,
               cardSetNumber: 6,
               key: "quickbeam",
            },
            "radagast":
            {
               name: "Radagast",
               isUnique: true,
               cost: 5,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.ISTARI],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM3_A_JOURNEY_TO_RHOSGOBEL,
               key: "radagast",
            },
            "rangerOfCardolan":
            {
               name: "Ranger of Cardolan",
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA1_THE_WASTES_OF_ERIADOR,
               cardSetNumber: 10,
               key: "rangerOfCardolan",
            },
            "ravenhillScout":
            {
               name: "Ravenhill Scout",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.DALE, Trait.SCOUT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D1_THE_REDHORN_GATE,
               key: "ravenhillScout",
            },
            "riderOfTheMark":
            {
               name: "Rider of the Mark",
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D2_ROAD_TO_RIVENDELL,
               key: "riderOfTheMark",
            },
            "rivendellMinstrel":
            {
               name: "Rivendell Minstrel",
               cost: 3,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.NOLDOR],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM1_THE_HUNT_FOR_GOLLUM,
               key: "rivendellMinstrel",
            },
            "rivendellScout":
            {
               name: "Rivendell Scout",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.SCOUT],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM2_THE_THREE_TRIALS,
               cardSetNumber: 26,
               key: "rivendellScout",
            },
            "rumil":
            {
               name: "Rúmil",
               cost: 4,
               willpower: 2,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.SILVAN, Trait.SCOUT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM2_THE_THREE_TRIALS,
               cardSetNumber: 28,
               key: "rumil",
            },
            "sailorOfLune":
            {
               name: "Sailor of Lune",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.SCOUT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_GREY_HAVENS,
               cardSetNumber: 12,
               key: "sailorOfLune",
            },
            "sarnFordSentry":
            {
               name: "Sarn Ford Sentry",
               cost: 3,
               willpower: 2,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN, Trait.SCOUT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_LOST_REALM,
               cardSetNumber: 5,
               key: "sarnFordSentry",
            },
            "saruman":
            {
               name: "Saruman",
               isUnique: true,
               cost: 3,
               willpower: 3,
               attack: 5,
               defense: 4,
               hitPoints: 4,
               traitKeys: [Trait.ISTARI, Trait.ISENGARD],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
               key: "saruman",
            },
            "silvanRefugee":
            {
               name: "Silvan Refugee",
               cost: 1,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS2_THE_DRUADAN_FOREST,
               key: "silvanRefugee",
            },
            "silvanTracker":
            {
               name: "Silvan Tracker",
               cost: 3,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.SILVAN],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
               key: "silvanTracker",
            },
            "silverlodeArcher":
            {
               name: "Silverlode Archer",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.ARCHER, Trait.SILVAN],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "silverlodeArcher",
            },
            "skinbark":
            {
               name: "Skinbark",
               isUnique: true,
               cost: 3,
               willpower: 0,
               attack: 4,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_LAND_OF_SHADOW,
               cardSetNumber: 6,
               key: "skinbark",
            },
            "snowbournScout":
            {
               name: "Snowbourn Scout",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.ROHAN, Trait.SCOUT],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "snowbournScout",
            },
            "sonOfArnor":
            {
               name: "Son of Arnor",
               cost: 3,
               willpower: 0,
               attack: 2,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.CORE,
               key: "sonOfArnor",
            },
            "squireOfTheCitadel":
            {
               name: "Squire of the Citadel",
               cost: 1,
               willpower: 0,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS5_THE_BLOOD_OF_GONDOR,
               key: "squireOfTheCitadel",
            },
            "theRiddermarksFinest":
            {
               name: "The Riddermark's Finest",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.CREATURE, Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM4_THE_HILLS_OF_EMYN_MUIL,
               key: "theRiddermarksFinest",
            },
            "treebeard":
            {
               name: "Treebeard",
               isUnique: true,
               cost: 4,
               willpower: 2,
               attack: 4,
               defense: 3,
               hitPoints: 5,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM6_THE_ANTLERED_CROWN,
               cardSetNumber: 146,
               key: "treebeard",
            },
            "trollshawScout":
            {
               name: "Trollshaw Scout",
               cost: 2,
               willpower: 0,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.SCOUT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D5_FOUNDATIONS_OF_STONE,
               key: "trollshawScout",
            },
            "vassalOfTheWindlord":
            {
               name: "Vassal of the Windlord",
               cost: 1,
               willpower: 0,
               attack: 3,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM5_THE_DEAD_MARSHES,
               key: "vassalOfTheWindlord",
            },
            "veteranAxehand":
            {
               name: "Veteran Axehand",
               cost: 2,
               willpower: 0,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.CORE,
               key: "veteranAxehand",
            },
            "veteranOfNanduhirion":
            {
               name: "Veteran of Nanduhirion",
               cost: 4,
               willpower: 0,
               attack: 3,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DWARF, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.KHAZAD_DUM,
               key: "veteranOfNanduhirion",
            },
            "veteranOfOsgiliath":
            {
               name: "Veteran of Osgiliath",
               cost: 3,
               willpower: 1,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.GONDOR, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA2_ESCAPE_FROM_MOUNT_GRAM,
               cardSetNumber: 29,
               key: "veteranOfOsgiliath",
            },
            "wanderingEnt":
            {
               name: "Wandering Ent",
               cost: 2,
               willpower: 2,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM5_CELEBRIMBORS_SECRET,
               cardSetNumber: 119,
               key: "wanderingEnt",
            },
            "wanderingTook":
            {
               name: "Wandering Took",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.HOBBIT],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.CORE,
               key: "wanderingTook",
            },
            "wardenOfAnnuminas":
            {
               name: "Warden of Annúminas",
               cost: 4,
               willpower: 0,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.DUNEDAIN, Trait.RANGER],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_LOST_REALM,
               cardSetNumber: 6,
               key: "wardenOfAnnuminas",
            },
            "wardenOfHealing":
            {
               name: "Warden of Healing",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.GONDOR, Trait.HEALER],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D4_THE_LONG_DARK,
               key: "wardenOfHealing",
            },
            "wardenOfHelmsDeep":
            {
               name: "Warden of Helm's Deep",
               cost: 3,
               willpower: 0,
               attack: 1,
               defense: 3,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_RING_MAKER,
               cardSubsetKey: CardSubset.TRM6_THE_ANTLERED_CROWN,
               cardSetNumber: 138,
               key: "wardenOfHelmsDeep",
            },
            "wardenOfTheHavens":
            {
               name: "Warden of the Havens",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 1,
               hitPoints: 3,
               traitKeys: [Trait.NOLDOR, Trait.WARRIOR],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_GREY_HAVENS,
               cardSetNumber: 6,
               key: "wardenOfTheHavens",
            },
            "warriorOfLossarnach":
            {
               name: "Warrior of Lossarnach",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.OUTLANDS],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS1_THE_STEWARDS_FEAR,
               key: "warriorOfLossarnach",
            },
            "watcherOfTheBruinen":
            {
               name: "Watcher of the Bruinen",
               cost: 2,
               willpower: 0,
               attack: 1,
               defense: 2,
               hitPoints: 2,
               traitKeys: [Trait.NOLDOR, Trait.WARRIOR],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.DWARROWDELF,
               cardSubsetKey: CardSubset.D3_THE_WATCHER_IN_THE_WATER,
               key: "watcherOfTheBruinen",
            },
            "weatherHillsWatchman":
            {
               name: "Weather Hills Watchman",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 0,
               hitPoints: 2,
               traitKeys: [Trait.DUNEDAIN],
               sphereKey: Sphere.LEADERSHIP,
               cardSetKey: CardSet.THE_LOST_REALM,
               cardSetNumber: 3,
               key: "weatherHillsWatchman",
            },
            "wellinghallPreserver":
            {
               name: "Wellinghall Preserver",
               cost: 3,
               willpower: 3,
               attack: 2,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.ENT],
               sphereKey: Sphere.LORE,
               cardSetKey: CardSet.ANGMAR_AWAKENED,
               cardSubsetKey: CardSubset.AA3_ACROSS_THE_ETTENMOORS,
               cardSetNumber: 61,
               key: "wellinghallPreserver",
            },
            "westfoldHorseBreaker":
            {
               name: "Westfold Horse-Breaker",
               cost: 2,
               willpower: 1,
               attack: 0,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM1_THE_HUNT_FOR_GOLLUM,
               key: "westfoldHorseBreaker",
            },
            "westfoldHorseBreeder":
            {
               name: "Westfold Horse-breeder",
               cost: 1,
               willpower: 1,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
               key: "westfoldHorseBreeder",
            },
            "westfoldOutrider":
            {
               name: "Westfold Outrider",
               cost: 2,
               willpower: 0,
               attack: 2,
               defense: 1,
               hitPoints: 2,
               traitKeys: [Trait.ROHAN, Trait.SCOUT],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.THE_VOICE_OF_ISENGARD,
               key: "westfoldOutrider",
            },
            "westRoadTraveller":
            {
               name: "West Road Traveller",
               cost: 2,
               willpower: 2,
               attack: 0,
               defense: 0,
               hitPoints: 1,
               traitKeys: [Trait.ROHAN],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM6_RETURN_TO_MIRKWOOD,
               key: "westRoadTraveller",
            },
            "whiteTowerWatchman":
            {
               name: "White Tower Watchman",
               cost: 3,
               willpower: 1,
               attack: 0,
               defense: 2,
               hitPoints: 3,
               traitKeys: [Trait.GONDOR],
               sphereKey: Sphere.NEUTRAL,
               cardSetKey: CardSet.AGAINST_THE_SHADOW,
               cardSubsetKey: CardSubset.ATS2_THE_DRUADAN_FOREST,
               key: "whiteTowerWatchman",
            },
            "wingedGuardian":
            {
               name: "Winged Guardian",
               cost: 2,
               willpower: 0,
               attack: 0,
               defense: 4,
               hitPoints: 1,
               traitKeys: [Trait.CREATURE, Trait.EAGLE],
               sphereKey: Sphere.TACTICS,
               cardSetKey: CardSet.SHADOWS_OF_MIRKWOOD,
               cardSubsetKey: CardSubset.SOM1_THE_HUNT_FOR_GOLLUM,
               key: "wingedGuardian",
            },
            "zigilMiner":
            {
               name: "Zigil Miner",
               cost: 2,
               willpower: 1,
               attack: 1,
               defense: 1,
               hitPoints: 1,
               traitKeys: [Trait.DWARF],
               sphereKey: Sphere.SPIRIT,
               cardSetKey: CardSet.KHAZAD_DUM,
               key: "zigilMiner",
            },
         },

         keys: function()
         {
            return Object.getOwnPropertyNames(AllyCard.properties);
         },

         keysBySphere: function(sphereKey)
         {
            InputValidator.validateNotNull("sphereKey", sphereKey);

            var keys = AllyCard.keys();

            return keys.filter(function(cardKey)
            {
               var card = AllyCard.properties[cardKey];

               return card.sphereKey === sphereKey;
            });
         },
      };

      AllyCard.keys().forEach(function(cardKey)
      {
         var card = AllyCard.properties[cardKey];
         card.cardSet = CardSet.properties[card.cardSetKey];
         if (card.cardSubsetKey)
         {
            card.cardSubset = CardSubset.properties[card.cardSubsetKey];
         }
         card.cardTypeKey = CardType.ALLY;
         card.cardType = CardType.properties[card.cardTypeKey];
         card.sphere = Sphere.properties[card.sphereKey];

         var imagePath = card.name;
         imagePath = imagePath.replace(/ /g, "-");

         card.imagePath = imagePath;
      });

      if (Object.freeze)
      {
         Object.freeze(AllyCard);
      }

      return AllyCard;
   });
